### PR TITLE
Add feature to populate max item stack

### PR DESCRIPTION
**Pull request by cpurules**
Good morning,

This feature adds a function that allows the user to double-click the 'Count' label in the item editor to auto-fill the field with the max stack for the item (appropriately using 0-based count numbering)

image

A few things to note about this feature:

- The max item counts are stored (in 1-based numbering) in **NHSE.Core\Resources\text\item_counts_json.txt** which is a JSON document.  The item ID is the key, and the max count is the value.
- To parse the JSON, I added the Json.NET NuGet package to the project.  I do not believe this NuGet package is Windows-specific, and have had someone test the new build on macOS using Mono with no issues.
- I know I am missing some item stacks (namely flower bags) but I believe I have gotten almost everything else.  Below is a list of the count mapping that was used.

```
simple wooden fence => 50
lattice fence => 50
earth egg => 30
stone egg => 30
leaf egg => 30
wood egg => 30
sky egg => 30
water egg => 30
heart crystal => 30
Bunny Day fence => 50
hedge => 50
pearl => 30
apple => 10
orange => 10
pear => 10
peach => 10
cherry => 10
coconut => 10
rusted part => 10
tree branch => 30
gold nugget => 30
iron nugget => 30
customization kit => 50
clump of weeds => 99
softwood => 30
wood => 30
hardwood => 30
brick fence => 50
clay => 30
elegant mushroom => 10
round mushroom => 10
skinny mushroom => 10
flat mushroom => 10
rare mushroom => 10
vertical-board fence => 50
bamboo lattice fence => 50
snowflake => 10
large snowflake => 10
corral fence => 50
country fence => 50
rope fence => 50
imperial fence => 50
straw fence => 50
iron fence => 50
spiky fence => 50
fish bait => 10
iron-and-stone fence => 50
zen fence => 50
stone fence => 50
barbed-wire fence => 50
acorn => 30
pine cone => 30
red ornament => 30
blue ornament => 30
gold ornament => 30
Nook Miles Ticket => 10
cherry-blossom petal => 10
star fragment => 10
large star fragment => 10
Capricorn fragment => 10
Aquarius fragment => 10
Pisces fragment => 10
Aries fragment => 10
Taurus fragment => 10
Gemini fragment => 10
Cancer fragment => 10
Leo fragment => 10
Virgo fragment => 10
Libra fragment => 10
Scorpius fragment => 10
Sagittarius fragment => 10
maple leaf => 10
```

This was requested by a member of a community I'm in and I feel there is value in having his built in to the application :)

Thanks,
Charlie

### CODE REVIEW

**Comment by cpurules** [comment]
Additionally - not related to this PR but to PRs in general - I noticed that a pull request triggers a build, presumably to ensure there are isn't a major breaking change.  This is obviously good, but this build then becomes the most recent build available to download at https://berichan.github.io/GetNHSE/

image

As a suggestion, builds should not appear on the GetNHSE page unless they occur due to a completed PR/merge/commit to master, rather than just from the PR being created - I am sure the risk here is obvious.  I am not sure what the best way to handle this is as I don't have a ton of experience with a CI/CD pipeline like this though

**Comment by kwsch** [comment]
Pull requests overriding last main build: would be something for @berichan to address on their end; maybe there's a way to query the azure pipeline api differently

**Comment by kwsch** [comment]
I'm not really a fan of using externally generated files, especially hand curated ones that can be outdated with each game patch.

The NHSE.Parsing sub-project contains all the logic for generating NHSE's tables and lookups from the bcsv files; I'd think the max stack value is stored in the ItemParam.bcsv as well. We should probably just add a binary/text file generator like the others instead (similar to recipe dictionary). That way we don't have to worry about the changes in each significant game update, as our programs will regenerate stuff for us :)

**Comment by cpurules** [comment]
That makes sense to me - to be honest I kind of felt like the JSON file was a little "hacky" and had the same thought about manual updates, but wasn't sure how else to go about it.  I'll look more into NHSE.Parsing and play around with it, hopefully I'll have something new here soon :)

**Comment by cpurules** [comment]
For Kurt, re: the pipeline/artifact - would it maybe make sense to run the build to ensure there are no compile-time errors but not actually publish the artifact unless there is a commit to master?  As mentioned I don't have a ton of experience with the pipelines but surely there is a way to only trigger the publish when there is a change to master?

On the topic of this PR - I've been able to successfully implement a read from ItemKind.bcsv (where the item stacks are stored - it is by item type and not by item).  Since it is an ItemKind -> ushort mapping I implement that as a dictionary and added a method to dump the dictionary to JSON, as I wasn't sure of another way to really represent that sort of mapping.

There is also a little bit of a lingering oddity around a couple of the types.  ItemKind.bcsv generalizes clothing labels, e.g. Tops, Bottoms, Shoes.  However the ItemKind enum in NHSE.Core splits these into more granular types.  Since clothing is not stackable (and IMO is unlikely to ever be stackable), and since parsing them anyway would throw an ArgumentException, I filtered them out ([see here](https://github.com/kwsch/NHSE/pull/396/commits/0499da131048424cafbf7737d81535f17f6854cf#diff-119932207a65ec558f9d23ccb46e1638R252)).  Not sure if there is a better way to handle this.

Finally:  I have updated GameBCSVDumper.ExtractInfo to include a call to the new DumpD[ictionary] method to create the JSON file for item stacks ([see here](https://github.com/kwsch/NHSE/pull/396/commits/0499da131048424cafbf7737d81535f17f6854cf#diff-119932207a65ec558f9d23ccb46e1638R96)).  However I'm still noticing that on build I run into an exception, which I suspect is because it can't find the JSON file.  Maybe this is me misunderstanding how NHSE.Parsing works -- is ExtractInfo built into the build process to generate the resources on the spot?  Or is it expected to be called externally, and then the resource files added to the project from there?  I ask because I do see the dumped binary files in the project (NHSE.Core\Resources\byte\item_kind.bin) but I don't see many of the text files (e.g. NHSE.Core\Resources\text\..\ItemKind.txt does not exist despite the DumpS call).

Thanks for your help & the info - it's much appreciated and it's really cool to see how some more of this works behind-the-scenes!

**Comment by cpurules** [comment]
I went through the code in NHSE.Parsing and see that it's not meant to be dynamic, just meant to be able to use to generate the files to include.  I understand your original comment better about 'externally generated files'.

I've added the NHSE.Parsing-generated ItemStack.json.txt as a resource in NHSE.Core and updated with a fresh push.  It should be good to go now, assuming you agree with the above points about the clothing being filtered out of the dump as well as dumping to JSON.

**Pull request merged**
