### PR TITLE
Pattern Edit Fix + New Icon + JP Strings

### PR DESCRIPTION
**Pull request by lottehime**
### Change 1:
Added fix for two parts of pattern import problems common across editors:
* PlayerID and TownID bytes need to be injected into the pattern data from the `personal.dat` offsets (or from one of many other sources) to set the patterns as owned and editable correctly. Added some code to get them from `personal.dat` and force overwrite to fix. Applies to normal and pro designs.  
* Flags exist in `main.dat` for if the player has edited the pattern slot and if not, the name will not be updated correctly on import. Added offsets for these and added code to flag them as edited on import to fix.

In reference to issues: https://github.com/kwsch/NHSE/issues/269 & https://github.com/kwsch/NHSE/issues/584
Can also be seen in issues for other ACNH editor projects.

Research/workings to backup conclusions above: https://github.com/lottehime/ACNH-Pattern-Research

### Change 2:
Added a new icon that supports up to 256px and is "distinct-ish".
Not sure if a welcome change, so feel free to reject.

### Change 3:
Added translations to MessageStrings_jp.txt.

Feel free to discuss any changes / issues / questions with me :)

### CODE REVIEW

**Comment by hunshikan** [comment]
This bug fix seems to have introduced another bug，When I copied other people's islands through the new version of NHSE, it seemed that there were some issues with the land, but the old version of NHSE performed normally

**Comment by lottehime** [comment]
Thanks for letting me know.
I'll look into it when I have some time. I have a feeling I know what has caused it.

**Comment by hunshikan** [comment]
[lottehime](https://github.com/lottehime)
[[DA-1608-5112-4385].zip](https://github.com/kwsch/NHSE/files/13691207/DA-1608-5112-4385.zip)
You can use this archive to export necessary files and overwrite them with your own archive to reproduce the problem

**Comment by lottehime** [comment]
> @lottehime [[DA-1608-5112-4385].zip](https://github.com/kwsch/NHSE/files/13691207/DA-1608-5112-4385.zip) You can use this game save to export necessary files and overwrite them with your own save to reproduce the problem

Thanks, aware of that - might be some crossed wires, what I want to know is the build number of the older NHSE you are using where the issue is not reproduced? I can of course compare the new builds to the one before this merge, but want to confirm against the exact version also. Thank you.

**Comment by hunshikan** [comment]
@lottehime 
Yes, the old version is completely fine

**Comment by lottehime** [comment]
It's OK, I'm not sure you understand what I am asking so don't worry about the question. I will look into it when I have time.

**Comment by lottehime** [comment]
@hunshikan issue identified and fix identified. Pattern data block offsets ``0x70 -> 0x71`` contain a byte sequence that is needed to flag it as placed and transparent. I will add an issue and implement the fix soon and make a PR to close it out.

@kwsch would it be acceptable for me to request the ability to help triage and assign issues (such as this one)? I would like to be more active in helping organize and get fixes happening for them as time permits. Thanks for considering and feel free to reach out.

**Comment by kwsch** [comment]
Added. Do whatever ya wanna do ;)

**Pull request merged**
