### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by yanisdreemurr**
I know my translations are not perfect everywhere, but i think it will be fine, if any person can help it would be with pleasure hehe

### CODE REVIEW

**Comment by berichan** [comment]
If your Japanese translations are anything to go by then these translations aren't valid.

You've used とにかく to translate "anyway" as a confirmation but とにかく is the "anyway" to change the conversation.
You've used 16 進値 to mean hexadecimal. This is what google translate gives you but it documentation it's 16進数値.
You've used 村人 to mean villager (animals) but this is used for villager (players only)

**Comment by yanisdreemurr** [comment]
Thank you very much berichan for your help, I will correct this as soon as possible!

**Comment by berichan** [comment]
I don't think machine translation is valid for end-user messages. There are other issues with the Japanese translation and isn't something you can fix yourself without knowing the language, and this likely extends to the other languages you've "translated" here.

**Comment by yanisdreemurr** [comment]
said in this sense, you are right,  I will still try to correct the different errors that you have cited to me and others in the different languages, in any case thank you for your help and your patient to explain to me hehe (I close this pull request)

**Pull request closed without merging**
